server:
  port: 8800


spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/lrh-oa?serverTimezone=GMT%2B8&userSSL-false&characterEncoding=utf-8
    password: lrh,903.520hhhh
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    host: 192.168.29.123
    port: 6379
    database: 0
    timeout: 1800000
    password: 20030706
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/lrh/auth/mapper/xml/*.xml